In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [10]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

In [11]:
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0],
              [1],  
              [1],
              [0]])

In [17]:
np.random.seed(42)  # For reproducibility
input_neurons = 2
hidden_neurons = 4
output_neurons = 1

W1 = np.random.rand(input_neurons, hidden_neurons)
W2 = np.random.rand(hidden_neurons, output_neurons)

B1 = np.random.rand(1, hidden_neurons)
B2 = np.random.rand(1, output_neurons)

learning_rate = 0.001
epochs = 100

In [16]:
print("Bobot W1 (input -> hidden):")
print(W1)
print("\nBobot W2 (hidden -> output):")
print(W2)
print("\nBias B1 (hidden layer):")
print(B1)
print("\nBias B2 (output layer):")
print(B2)

Bobot W1 (input -> hidden):
[[0.6926181  0.28276959 0.22417113 0.54536569]
 [0.71546741 0.41959809 0.97793017 0.67863605]]

Bobot W2 (hidden -> output):
[[0.41258093]
 [0.33586928]
 [0.27619441]
 [0.65637903]]

Bias B1 (hidden layer):
[[0.42917203 0.0516951  0.39148952 0.72363442]]

Bias B2 (output layer):
[[0.08687172]]


In [13]:
for epoch in range(epochs):
    hidden_input = np.dot(X, W1) + B1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + B2
    final_output = sigmoid(final_input)

    error = y - final_output
    delta_output = error * sigmoid_derivative(final_input)

    error_hidden = delta_output.dot(W2.T)
    delta_hidden = error_hidden * sigmoid_derivative(hidden_output)

    W2 += hidden_output.T.dot(delta_output) * learning_rate
    W1 += X.T.dot(delta_hidden) * learning_rate
    B2 += np.sum(delta_output, axis=0, keepdims=True) * learning_rate
    B1 += np.sum(delta_hidden, axis=0, keepdims=True) * learning_rate

In [14]:
print("Output setelah Training:")
print(final_output)

Output setelah Training:
[[0.75370051]
 [0.79520767]
 [0.78387443]
 [0.81432855]]
